#MYSQL
spring:
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true
  
  datasource:
    url: jdbc:mysql://localhost:3306/study_db?autoReconnect=true&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 1234
    
#security 설정
security:
  user:
    name: user
    password: test
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:9093/oauth/token_key 
    client:
      client-id: foo
      client-secret: bar
    authorization:
      token-key-access: isAuthenticated()
#로깅레벨
logging:
  level:
    ROOT: error
#포트
server:
  port: 9093